### ISSUE TITLE
Suggestion: drop dependency on React.createElement

### ISSUE THREAD

**Issue by axefrog** [alangpierce/sucrase#207]
Not sure if you're aware, but JSX is used for other projects too, such as virtual-dom, snabbdom, surplus and others. It would definitely be worthwhile making the element factory function configurable, rather than hardcoding it to React.createElement.

**Comment by alangpierce** [comment]
Makes sense! I've wanted to keep it low-configuration with good defaults, but agreed that non-JSX React would be good to support.

From the docs for https://github.com/Swizz/snabbdom-pragma, looks like I can probably just add a new option `jsxPragma` that's a string for the code to use instead of `React.createElement`. Note that the `React` needs to get transformed to `_react2.default` in some cases [(example)](https://sucrase.io/#code=%0Aimport%20React%20from%20'react'%3B%0Aconst%20x%20%3D%20%3CFoo%20%2F%3E%3B), so it's a little less trivial than just dropping the new code in, but still shouldn't be so bad, I think.

**Comment by axefrog** [comment]
Snabbdom's a popular example, but there are many other projects too, so it might not be quite as simple as that, as you'd only be able to say you support projects that explicitly implement that feature. Keep the sensible default, I agree, but being able to optionally override the name of the factory function would allow everyone to use sucrase as-is, without bothering you about it, and without bothering the owners of whatever platforms they want to integrate with.
