### ISSUE TITLE
webpack-loader with object rest spread plugin fails parsing

### ISSUE THREAD

**Issue by dan-lee** [alangpierce/sucrase#225]
When trying to run sucrase with the `webpack-loader` and `webpack-object-rest-spread-plugin` I get the following error:

> ERROR in ./src/Main.jsx
Module parse failed: this.applyPluginsBailResult is not a function
You may need an appropriate loader to handle this file type.
TypeError: this.applyPluginsBailResult is not a function

Versions used:
```
webpack: 4.8.3
sucrase: 2.2.0
@sucrase/webpack-loader: 1.0.2,
@sucrase/webpack-object-rest-spread-plugin: 1.0.0
```

**Comment by alangpierce** [comment]
Thanks for reporting. Since you're on webpack 4, I think object rest/spread should actually work without `webpack-object-rest-spread-plugin`. I wrote that plugin before webpack 4 came out, and it's still needed on 3 or earlier. Could you try removing that plugin and see if it works and that you can still have object rest/spread in your code?

I'll update the docs to say that `webpack-object-rest-spread-plugin` is not needed in webpack 4. It looks like webpack 4 changed enough to break the plugin, so I'll also see if I can make it print a warning and do nothing if it detects that you're on webpack 4.

**Comment by dan-lee** [comment]
Oh yeah, it works without. I just blindly assumed it was necessary.
Thank you, and keep up the nice project :)

**Comment by alangpierce** [comment]
Thanks, glad to hear! I'll actually reopen to track the task of updating the docs and maybe adding a runtime check.

**Comment by iki** [comment]
@alangpierce Actually, I get the above error with webpack4, typescript and webpack-object-rest-spread-plugin, and if I remove the spread plugin, I also need to disable fork-ts-checker-webpack-plugin to compile ok, otherwise the checker plugin reports first spred operator as error.

Is there any workaround? What checker do you use?

**Comment by iki** [comment]
@alangpierce thanks! updating acorn resolved that: https://github.com/webpack/webpack/issues/5548#issuecomment-395460827

**Comment by alangpierce** [comment]
Cool, glad to hear.
