### ISSUE TITLE
"sucrase-node" in memory transpiling

### ISSUE THREAD

**Issue by abelcha** [alangpierce/sucrase#262]
Is there any plan to implement a in memory transpiling cli, similar to [babel-node](https://babeljs.io/docs/en/babel-cli/#babel-node) ?

**Comment by alangpierce** [comment]
Yep! Thanks for filing an issue, I didn't have anything tracking this, but agreed that it would be useful.

You can already do `require('sucrase/register')` to register a require hook, but that needs to be done in JS code rather than it being a drop-in replacement for node.

I actually already have a temporary version used for Sucrase's build scripts, but I believe it's missing a lot of the details that babel-node gets right, so I haven't published it yet: https://github.com/alangpierce/sucrase/blob/master/script/sucrase-node
