### ISSUE TITLE
enum keys cannot be keywords

### ISSUE THREAD

**Issue by kiliancs** [alangpierce/sucrase#392]
Using Sucrase 3.9.2

```ts
enum Example {
    default
}
```

results in code that, when evaluated, fails with `SyntaxError: missing variable name`, `Uncaught SyntaxError: Unexpected token default` or `Unexpected keyword 'default'`, depending on the engine.

Not a huge deal because this breaks the casing conventions and it's probably not a good idea to use "default" in this context anyway, but I can testify to real code existing in the world like this (from migrations from vanilla js), and this works with tsc.

https://sucrase.io/#code=enum%20Example%20%7B%0A%20%20%20%20default%0A%7D

Edit: removed `export` and explicit value in order to simplify the example

**Comment by kiliancs** [comment]
If you are ok with that, I'll try to fix this and create a pull request making the output closer to the one from TypeScript.

**Comment by alangpierce** [comment]
Sounds good! However I remember this being a case where copying the TS output exactly is probably unreasonable. TS does constant folding, e.g. [this playground snippet](https://sucrase.io/#code=enum%20Example%20%7B%0A%20%20%20%20a%20%3D%201%2C%0A%20%20%20%20b%20%3D%20a%20%2B%202%0A%7D), and Sucrase doesn't really have a way of parsing the expressions in order to evaluate them; it just moves code snippets around. There might be a way to make it work with `eval`, but that's fishy for various reasons and won't work in webassembly (which I'm hoping to target eventually via AssemblyScript). So that was my motivation for declaring each intermediate enum value as a variable that can then be referenced by later enum value expressions.

My current impression is the best approach is to find a way to use a variable name other than `default`. Also worth noting that you can't do `x = default + 1` in a later step, so it's not actually needed to make it a variable. I don't have a great answer about the exact code transform, but happy to brainstorm. It would be nice to avoid the need for a list of all keywords (though one sort of exists already in the parser), though it's possible that's really hard to avoid here.

**Comment by kiliancs** [comment]
Yeah... I realized we'd rather not enter the evaluation rabbit hole as soon as I looked at the code of the transformation. The only other option I can think of is parsing the expression (`default + 1`) in your example and replace "default" with `Foo["default"]` (for an enum named `Foo`). I'm not sure how desirable or easy this is.

Right now, for the sake of moving forward, I have a branch that doesn't declare any `const` for each enum entry, so where Sucrase 3.9.2 outputs:

```js
const A = "eh"; Foo["A"] = A;
const B = "bee"; Foo["B"] = B;
const C = "sea"; Foo["C"] = C;
```

my branch outputs

```js
Foo["A"] = "eh";
Foo["B"] = "bee";
Foo["C"] = "sea";
```

Similarly, this 3.9.2 output:

```js
const A = 0; Foo[Foo["A"] = A] = "A";
const B = A + 1; Foo[Foo["B"] = B] = "B";
const C = B + 1; Foo[Foo["C"] = C] = "C";

```

becomes

```js
Foo[Foo["A"] = 0] = "A";
Foo[Foo["B"] = Foo["A"] + 1] = "B";
Foo[Foo["C"] = Foo["B"] + 1] = "C";
Foo[Foo["default"] = Foo["C"] + 1] = "default";
```

Of course this fails as soon as a value expression references some other enum entry.

**Comment by alangpierce** [comment]
Hmm, yeah this is tricky 😕. I'd rather not knowingly break even obscure cases, but hopefully there's a creative way to make it work in general without adding a ton of complexity.

> The only other option I can think of is parsing the expression (default + 1) in your example and replace "default" with Foo["default"]

I think `default + 1` actually is a TS error since it's not a valid JS expression, so we can assume that won't come up. I think a working approach would be "if the enum key is a keyword, emit it without the variable", and that may end up being the best approach, but a concern of mine is that JS has a lot of half-keywords like `await` with complex behavior.

**Comment by alangpierce** [comment]
Ooh, I just thought of an idea that could work well: only declare variables that are used as an identifier in some another enum value. Since `default` is never allowed to be used in a later expression it would never show up in valid code, so we'd never declare the variable. I think this should let us avoid declaring invalid variables without needing a list of invalid variables names.

This requires scanning ahead to look through the other enum values, but we've already tokenized them and can get their identifier strings via `identifierNameAtIndex` and related functions.

Annoyingly, this appears to be legal:
```typescript
enum Example {
  default = 1,
  foo = {default: 3}.default,
}
```
but I think limiting to `IdentifierRole.Access` and `IdentifierRole.ObjectShorthand` should work. Shadowed variable names could cause false positive variable declarations, but that's ok since we only really want to avoid variable declarations for things that are invalid in JS.

I guess that complexity maybe means the "big list of invalid names" isn't so bad, but unfortunately the contextual keyword vs regular distinction already in the parser isn't enough (e.g. `of` and `private` are both considered contextual keywords, but `of` is a valid variable name and `private` isn't). Fortunately, Sucrase always assumes strict mode (since it assumes it's compiling a module), so we don't need to dynamically decide which keywords are legal.

I think I'd be ok with either approach.

Are you still interested in working on this? Happy to provide any additional guidance. I can also try taking it on at some point if you're not feeling up for it.

**Comment by kiliancs** [comment]
I'm willing to give this a try, but it will probably take a few days between getting the time and getting it done, so feel free to go ahead with a fix if you have higher availability.

**Comment by alangpierce** [comment]
I probably won't have time until this weekend, so feel free to start on it (and let me know if you do).
