### ISSUE TITLE
How to get max performance out of sucrase in a CRA app?

### ISSUE THREAD

**Issue by yang** [alangpierce/sucrase#421]
On a ~100kLOC TSX codebase running in create-react-app 2.x, we see the following measurements:

```
full build of codebase:

- sucrase: 20s
- babel: 43s

incremental build (edit one file) in webpack-dev-server:

- sucrase: 2s
- babel: 3.3s
```

We really only care about the incremental build times.  We haven't yet started digging into why we're not seeing nearly as impressive numbers from sucrase, but short of doing a profiler deep-dive into webpack, were wondering if you have any tips/pointers on anything we might be missing, be it in our webpack config or elsewhere.  The main change we made (vs stock create-react-app) was replacing the babel-loader with @sucrase/webpack-loader (with jsx, typescript, react-hot-loader enabled).

We also disabled the ForkTsCheckerWebpackPlugin (applies to numbers for both sucrase and babel above), which made a big difference - here are those numbers for completeness / for the curious:

```
full build:
- sucrase with tsc: 28s
incremental build:
- sucrase with tsc: 23s, 19s
```

We also checked if eslint was running, but that's only running over js files (of which we have none).

Sorry we aren't able to share anything reproducible here - I know that would be ideal.

**Comment by alangpierce** [comment]
Hey @yang!

My experience with Webpack is about the same as yours, so unfortunately I don't think there's much more that can be improved with just Sucrase. Webpack is complicated and does a lot of different things, and JS transpile time is part of that but certainly not all of it. My guess is that previously for you, Webpack startup had 18 seconds of internal Webpack work and 25 seconds of Babel work, and now it has 18 seconds of internal Webpack work and 2 seconds of Sucrase work.

Like Babel, Webpack works by running a regular JS parser on all everything being processed (and for Webpack I think it includes everything you use in node_modules), and from my profiling I think that's a big part of where Webpack spends its time. I've experimented with a Webpack fork that uses the Sucrase parser to skip unnecessary parsing work, but it's certainly not trivial. The same principle could still apply, though: the JS transformations it does while bundling are not *that* complicated, so there's room to take shortcuts in the parser for better performance. That's a whole other project, though. Someday... :smile:

I'm actually surprised that incremental build time got better; I thought it would just recompile the one file that changed, meaning Babel -> Sucrase would change it from 20ms to 1ms to recompile or something tiny like that. For Webpack use cases, I've mostly measured it in terms of startup time, which is relevant at my work since we sometimes run into Webpack bugs when switching branches that require restarting Webpack (particularly when porting JS to TS files).

At my work, we use happypack to run Sucrase in a single background process, so that's one thing to try, but my impression is it doesn't actually make a measurable difference.

The Webpack 4 upgrade improved perf a lot from my experience, so in case you're not on Webpack 4, would be a good thing to do.

For me, the biggest benefit from Sucrase has been running tests in node (without Webpack), which is a lot simpler in that it doesn't need to bundle the JS files. Previously for me, cold startup of tests would take a few minutes to compile everything, and warm startup would still be a bit slow to load the whole cache, and also be fragile because the caching had bugs. With Sucrase there's no cold/warm distinction and it's always faster than the prior cached time. (That was with the Babel 6 babel-register implementation, though, so it might be different in Babel 7.)

In terms of "is Sucrase worth it at all?", it's also worth noting that Sucrase avoids the need for a transpile cache, and it also emits JS that's often a bit more developer-friendly than what Babel/tsc give (e.g. line numbers are preserved).

**Comment by yang** [comment]
Super helpful response, Alan, thanks!  Especially to know that your
profiling seems to point toward Webpack work and specifically its parser
(never knew it had an Acorn-based parser).

I should mention we're sticking with sucrase (despite missing decorators!).

We are indeed using webpack 4 (and create react app 2).

**Correction on my measurements**: when I was measuring performance
earlier, I tried commenting/uncommenting out a line of code in a large
file.  I would do this a few times to get a stable measurement, since it
seemed to take shorter on subsequent tries.  Well, it turns out that Babel
**caches multiple historical versions of your source**, so by flipping
between just two versions of the file, I believe I was merely measuring the
cached times for Babel.  react-scripts enables this cache in babel-loader
by specify `cacheDirectory: true`.

When I instead am always saving new unseen versions of the code, I see much
slower times for Babel - those 3.3s become 8.5s.  So even for the
incremental case, it's a large win.

Like you, I'm still surprised there is such a big difference, since the
babel transpiler on sucrase.io reports taking 330ms.  (I'm surprised in
general at how long frontend code builds take - seems miles apart from the
experience in browser playgrounds.)  I'm very eager to hear any clues as to
why this discrepancy / if we might be Doing It Wrong.

**Comment by yang** [comment]
(Re-posting last message with fixed formatting:)

Super helpful response, Alan, thanks!  Especially to know that your profiling seems to point toward Webpack work and specifically its parser (never knew it had an Acorn-based parser).

I should mention we're sticking with sucrase (despite missing decorators!).

We are indeed using webpack 4 (and create react app 2).

**Correction on my measurements**: when I was measuring performance earlier, I tried commenting/uncommenting out a line of code in a large file.  I would do this a few times to get a stable measurement, since it seemed to take shorter on subsequent tries.  Well, it turns out that Babel **caches multiple historical versions of your source**, so by flipping between just two versions of the file, I believe I was merely measuring the cached times for Babel.  react-scripts enables this cache in babel-loader by specify `cacheDirectory: true`.

When I instead am always saving new unseen versions of the code, I see much slower times for Babel - those 3.3s become 8.5s.  So even for the incremental case, it's a large win.

Like you, I'm still surprised there is such a big difference, since the babel transpiler on sucrase.io reports taking 330ms.  (I'm surprised in general at how long frontend code builds take - seems miles apart from the experience in browser playgrounds.)  I'm very eager to hear any clues as to why this discrepancy / if we might be Doing It Wrong.

**Comment by yang** [comment]
Here are some more performance measurements, this time comparing testing speedups.  This is just using create-react-app 2.0's testing infrastructure over several hundred tests, comparing babel and @sucrase/jest-plugin.

- babel: 294s
- sucrase: 101s

I'm guessing that something in jest's transform architecture is keeping sucrase from reaching its full speedup potential, but I know even less about jest than I do about webpack.  Not sure if you have any other insights here @alangpierce.

**Comment by alangpierce** [comment]
@yang I don't know a ton about Jest internals, but one thing I learned recently is that it automatically caches transpile results, which can certainly affect these things. I had to disable that here so I could better iterate on Sucrase itself: https://github.com/alangpierce/sucrase/pull/429 . I was going to say "caching doesn't help when you're using Sucrase", but interestingly, uncached Sucrase was about 2x slower than cached Sucrase on very small cases (about 1 second vs 0.5 seconds, IIRC). I certainly don't expect that to be 500ms of Sucrase time, so there may be some other differences in what Jest is doing.

What do those 294s/101s include? Is it the time of actually running the tests themselves, or some way of isolating transpile time? Generally tests involve transpile, importing all files, and running the tests themselves, and Sucrase can only make the transpile part faster.

**Comment by yang** [comment]
Disregard my numbers - I did try to record test times by redefining `it()` and subtracting that sum, but I failed to account for `beforeEach()`, module init, and parallelism (e.g. some threads taking up CPU to run tests while others are building). This will be trickier...

**Comment by alangpierce** [comment]
Closing this for housekeeping purposes, but happy to continue the discussion!
