### ISSUE TITLE
Please document how can I test sucrase

### ISSUE THREAD

**Issue by kdy1** [alangpierce/sucrase#423]
Sucrase's readme says it can't handle const enum but it says it successfully compiles tslint which uses const enum.

**Comment by alangpierce** [comment]
Hey @kdy1!

Agreed the initial note about `const enum` could be more clear. Later down in the README, it says "For example, TypeScript const enums are treated as regular enums rather than inlining across files.", so that's how it works. Basically the `const` doesn't do anything when you're using Sucrase, but you still might have a production build using tsc that does cross-file inlining.

For TypeScript, Sucrase mostly tries to mimic the behavior of TypeScript's `transpileModule` method, which is a bit more forgiving than Babel. TypeScript exposes the `isolatedModules` typechecking flag to ensure that your code can be safely transpiled on a file-by-file basis (by giving errors for ambient const enums, namespaces, and a few others), so the Sucrase documentation says that you should enable that flag for typechecking, and I'd recommend you document the same thing for swc.

You could also follow Babel's behavior, but Babel is a bit stricter and wouldn't be able to compile tslint. Some differences I know:
* Babel disallows *all* const enums. `ts.transpileModule` and Sucrase compile them as regular enums. `isolatedModules` only disallows ambient const enums (ones in a .d.ts file).
* Babel disallows `import a = require('a');`. `ts.transpileModule` and Sucrase compile them to `const a = require('a');`.
* Babel completely disallows namespaces. Sucrase just removes them (since often the only have types). `ts.transpileModule` compiles them in a way that won't really work with import/export behavior.

Also worth noting that Sucrase intentionally is not an error checker, and will make a best-effort attempt at compiling whatever code you give it. (`ts.transpileModule` also behaves like that.) This keeps the project simpler and avoids the performance cost of tracking errors.

As for how you can test it, here's how to run it on the example projects:
```
yarn
yarn build
yarn run-examples
# Or you can run a single example like this
yarn run-examples tslint
```

And, of course, https://sucrase.io is the easiest way to get a feel for how it compiles different syntax.
