### ISSUE TITLE
RegExp feature support

### ISSUE THREAD

**Issue by mathiasbynens** [alangpierce/sucrase#434]
First off, thank you for this amazing project!

I noticed that Sucrase doesn't support [modern regular expression features](https://mathiasbynens.be/notes/es-regexp-proposals) such as Unicode property escapes or the `dotAll` flag, even though they aren't yet supported in all browsers.

Example: https://sucrase.io/#selectedTransforms=&code=%2F%5Cp%7BScript%3DGreek%7D%2Fu (The generated code fails in Firefox, for example.)

Has support for these features been considered? (Babel and Bublé use [regexpu-core](https://github.com/mathiasbynens/regexpu-core) to implement support for these features.)

If you don't want to support this class of features, perhaps it would make sense to explicitly call these out in the README under [unsupported features](https://github.com/alangpierce/sucrase#unsupported-syntax). WDYT?

**Comment by alangpierce** [comment]
Hey @mathiasbynens, thanks for the kind words. 😄

The newer regex features are on the boundary where it's a bit unclear whether to include them in Sucrase, but I think at the moment I'd prefer not to. Given that the features are available in Chrome and Node and hopefully will be in Firefox soon enough, I think they're mature enough that Sucrase doesn't need to implement transforms for them. But I'm certainly willing to change my mind if there's enough demand for it. Thanks for surfacing, though, I'll update the README to mention this alongside the note about BigInt.

The main motivation is that I want to keep the project simple. I do a bit of future-JS transpiling for practical reasons (most notably class fields), but I prefer to keep that to a minimum and instead focus on language extensions (JSX, TS, Flow) and leave the real JS features for real JS engines. I'm also hesitant to pull in new dependencies, especially since they would likely make it harder to compile the code to WebAssembly in the future. Realistically, setting Sucrase up to use regexpu-core probably wouldn't be *that* hard, just a little extra complexity in a project that's already hard to keep in my head.

To be clear, all this means is that *developers using Sucrase can't use Firefox for development if they want to use new regex features*. Sucrase projects should generally still use Babel for production builds, meaning that end users can still use Firefox (and IE) just fine. For development, developers using Sucrase need to either hold off on the regex features for a little bit longer or use Chrome or Safari for development.
