### ISSUE TITLE
Readonly arrays and readonly tuples

### ISSUE THREAD

**Issue by aleclarson** [alangpierce/sucrase#437]
Coming in TypeScript 3.4.0 ([link](https://devblogs.microsoft.com/typescript/announcing-typescript-3-4-rc/))

```ts
type A = readonly string[]
type B = readonly [string]
```

[Playground link](https://sucrase.io/#code=type%20A%20%3D%20readonly%20string%5B%5D%0Atype%20B%20%3D%20readonly%20%5Bstring%5D)

**Comment by alangpierce** [comment]
Thanks for flagging! Looks like Babel updated everything on its end ( https://github.com/babel/babel/issues/9502 ) so it should just be a matter of porting over all recent Babel parser changes. (No Sucrase transform changes should be needed since it all falls under the existing "remove all type tokens" rule.)
