### ISSUE TITLE
Explicitly state which ES version is supported

### ISSUE THREAD

**Issue by BeeeQueue** [alangpierce/sucrase#528]
Nowhere in the readme does it state what ES version this tool transpiles to, and it would be a very useful thing for people to know if they want to adopt the tool.

e.g. if someone knows they support evergreen browsers up to 3 versions back, they could find out exactly what minimum ES version that corresponds to (ES2018 for example).

**Comment by Raynos** [comment]
It removes type annotations. So if you use ES6 subset of typescript then its ES6.

if you use ES2018 subset of typescript its ES2018

If you use ES5 subset of typescript its ES5

**Comment by BeeeQueue** [comment]
I see what you mean, changing typescript's `target` would change the output.

I still see the use-case for people who don't use typescript, as they are most likely using the latest features with `preset-env`.

**Comment by alangpierce** [comment]
Hey @BeeeQueue, while Sucrase does transpile some JS features, unfortunately there isn't a simple description in terms of ES versions. The closest thing you could try to say is "Sucrase accepts ES2020 and transforms it to ES2018", but that's wrong in a few ways:
* Sucrase supports class fields and numeric separators, which have not made it into an ES version yet. (I use https://github.com/tc39/proposals/blob/master/finished-proposals.md and https://github.com/tc39/proposals to track JS proposals, so that's what I'm referring to.)
* Sucrase does *not* transpile BigInt, since it generally cannot be transpiled. However, it is supported by recent versions of Node, Chrome, and Firefox (but not Safari), so depending on context you may be able to use it.
* Sucrase does not attempt any polyfills for new standard library functions.
* ES modules (`import`/`export`) have had their syntax standardized since ES2015, but there are a lot of nuances in thinking through whether and how to transpile them, and it's generally independent of ES version.

I think a better mindset, like @Raynos was mentioning, is to start by pretending the Sucrase does not provide *any* help, and by looking at what JS features are supported by your target runtime(s). This may mean tracking down compatibility tables with the major browsers, since browsers generally don't stick to exact ES versions. Then throw in all of the features from "These proposed JS features are built-in and always transformed" in the README (optional chaining, nullish coalescing, class fields, export namespace, numeric separators, optional catch). Those features you can use even if they're not supported by your runtime.

Also note that the long-term vision is to drop support (in a semver-major change) for all of these features once they're common in node and browsers. Sucrase's primary goal is to transpile modern source code (which may have TS, JSX, or Flow syntax) to code that can be run in a modern dev environment. Currently, the gap between those two includes some JS features, but I expect that that gap will narrow over time as JS engines support new syntax and new syntax features become less exciting and more incremental.

My hope was for the [transforms](https://github.com/alangpierce/sucrase#transforms) section of the docs to make the behavior clear. Let me know if you have any concrete thoughts on how the docs could be improved. I wouldn't strongly object to the "ES2020 compiles to ES2018, with caveats" phrasing, but I worry a little about it setting the wrong expectations.

**Comment by BeeeQueue** [comment]
Hm. Do you think it would be a good idea to add it to something like the [compat-table](https://kangax.github.io/compat-table/es6)?
