### ISSUE TITLE
Support for private class fields

### ISSUE THREAD

**Issue by benmccann** [alangpierce/sucrase#560]
It looks like support was added in TypeScript 3.8: https://www.valentinog.com/blog/private/#private-class-fields-in-typescript

It seems not to be supported yet in `sucrase`. I get the error `Usage of undeclared private name` when I try to use `#` in `sucrase`

**Comment by nifgraup** [comment]
The issue is that # is dropped when declaring:
```
class App extends Component {
  #property = false;
  handler = () => {
    this.#property = true;
  }
}
```
is turned into
```
"use strict";class App extends Component {constructor(...args) { super(...args); App.prototype.__init.call(this);App.prototype.__init2.call(this); }
  __init() {this.property = false}

  __init2() {this.handler = () => {
    this.#property = true;
  }}
}
```

**Comment by alangpierce** [comment]
Thanks for reporting, and sorry for the delay in responding. Thanks @nifgraup for putting up https://github.com/alangpierce/sucrase/pull/570 , though as I mentioned in that thread, I think the best approach for a near-term solution is to preserve the private property declaration `#property = false;` so that it appears in the output code. I put up a PR to do that at https://github.com/alangpierce/sucrase/pull/574 .

To be clear, this means that private fields will work *when the underlying JS engine supports them*, which as of this writing means node >= 12 and latest Chrome and Edge. As of this writing, Firefox has private fields working behind a flag (but not on by default) and Safari has it working in Safari Technology Preview but not on stable.

It's certainly a reasonable feature request to transpile private fields; it has some subtleties, but I think could be done in a reliable way via symbols or name mangling. If anyone needs that use case, feel free to reopen this issue or file a new one, and I'd be happy to accept a PR or provide thoughts, or I may be able to implement it myself if I have time.
