### ISSUE TITLE
Produce Babel AST?

### ISSUE THREAD

**Issue by Gregoor** [alangpierce/sucrase#597]
Heya,

I was wondering if it was feasible to produce a Babel AST equivalent tree from the sucrase's representation? Or would you expect the gains in parsing speed to be negligible enough for it not be a worthy endeavour?

Hope it's alright that I use issues for a very-likely-out-of-scope question, ofc feel free to close if you want me to take it somewhere else.

🥂

**Comment by alangpierce** [comment]
Hi @Gregoor , sorry for the delay in responding to this. Questions like this are always welcome, and this is a good place for them. 😄

Sucrase's representation is just a list of tokens, and it would be pretty hard to build an AST from that (about as hard as writing a completely separate parser). One approach could be to add back the AST-generating code that I removed after forking the Babel parser, but that feels pretty hard to get right. I think probably a better approach here would be to re-fork Babel's parser and specialize it to your needs. There were a number of speed-ups that I did that are unrelated to removing the AST, so you might be able to do the same sorts of things.

Most of the speed-ups that I did were in early 2018, so you might be able to get inspiration from those: https://github.com/alangpierce/sucrase/commits/main?after=38b66f3009feb76750a799deea211adcc83574f1+314&branch=main

Some examples that come to mind:
* Remove validation code. A *lot* of complexity in the Babel parser is around *failing* when it sees incorrect code and providing helpful error messages, and many of these checks can be removed for better performance. Dropping these checks often also leads to unused parameters and state fields, which can then be removed to speed up function calls and state cloning.
* Drop support for non-strict mode. For example, I remember complexity around octal literal parsing that I was able to remove.
* Remove plugin/flag checks (e.g. https://github.com/alangpierce/sucrase/commit/2423baf3bd4a7a5dd6f6f8e2e030426771e1e950 )
* Make state cloning explicit rather than dynamic ( https://github.com/alangpierce/sucrase/commit/aa9e4fc222f2e13b9862252f322b068adf63210c )
* Switch the parser code structure from a dynamically-created ~10-level-deep class hierarchy to plan function calls ( https://github.com/alangpierce/sucrase/commit/c15d70751b67f3464d8c165504f1b54c060683bc )
* Rework `readWord` to improve performance ( https://github.com/alangpierce/sucrase/commit/3b0e3ab3a4751bb4c6d4456a2075d6eb52541706 , https://github.com/alangpierce/sucrase/commit/196f86e97a86354cd599016d88a77e12914421c7 )

It's hard to say for sure, but I bet you'd get at least a 2x speedup with all of those combined, possibly quite a bit more.

Hope that's helpful!

**Comment by Gregoor** [comment]
Very helpful, thank you for giving such great detail. I already learned things by reading those commits! Also love how you made the Babel code readable in the process!

For my efforts I'm also [flirting with just using swc](https://github.com/swc-project/swc/issues/1392) which seem to have some level of interest in having babel AST compatibility. That would suit me well, as I don't have too much parser writing (and maintaining) experience.

Anyway, thanks again, I was really happy to get such an in-depth take from you.
