### ISSUE TITLE
Full-fledged support for const enum

### ISSUE THREAD

**Issue by StreetStrider** [alangpierce/sucrase#599]
The thing about const enums is that they have no footprint in generated code except for inlined constant values itself.
([example with TS4](https://www.typescriptlang.org/play?#code/FAUwdgrgtgBAogRhgbxgQQDQwEJYMIwC+wwyxwAZhGAMYAuAlgPZgwVIAUIAXPAgJQoYAJxB0Iw1iCKUEHRADo0-EmRI0WAZzoxw0eACYhmHPhlVajFmyNdecA4NSjxk3eYPyDSlUA))
Would it be too hard/expensive to support such form in sucrase?

**Comment by alangpierce** [comment]
Hi @StreetStrider, thanks for the request, and sorry for the delay.

Const enums are one of several older TypeScript features that are actually impossible to implement in Sucrase, so that's why they're not supported. Sucrase operates on each file independently (like Babel and like the `transpileModule` mode in TypeScript), so if you have `Direction.Up` in one file and `const enum Direction ...` in another file, Sucrase has no way to inline the constant value since it doesn't know it. Keeping the compilation contained to each file (rather than potentially needing codebase-wide name resolution) is important both for performance and for ease of use.

Sucrase could potentially implement some best-effort support for const enums within each file, but I don't think it's worth it since it would add quite a bit of complexity and it would be an incomplete solution. If inlining is important for performance, my recommendation is to run Sucrase for development builds and the full TypeScript compiler for production builds.

For what it's worth, my experience is that const enums don't measurably improve performance. Sucrase used to use const enums in several heavily-used places, but I found that regular enums weren't any slower (or the effect was small enough that I couldn't measure it). The V8 engine does a lot of smart optimizations, so I think it's able to do essentially the same optimization at runtime.

It's also worth noting that const enums go against the current [TypeScript Design Goals](https://github.com/microsoft/TypeScript/wiki/TypeScript-Design-Goals), since it's a situation where TypeScript will "emit different code based on the results of the type system". For all newer features, the TypeScript compiler's responsibility is just to remove the type annotations, not to modify or optimize the JS portion of the code. So my view is that const enums are a relic from the early days of TypeScript, and for any new code I prefer to use regular enums (or objects, [as described in the handbook](https://www.typescriptlang.org/docs/handbook/enums.html#objects-vs-enums)).

**Comment by StreetStrider** [comment]
@alangpierce hello. That is fair, I agree with you in general. Thank you for the answer.
