### ISSUE TITLE
Comma Operator in JSX expressions is wrong

### ISSUE THREAD

**Issue by nmain** [alangpierce/sucrase#613]
Code:
```jsx
<a b={c,d}>{e, f}</a>
```

Sucrase output:
```js
"use strict";
const _jsxFileName = "sample.tsx";
React.createElement('a', { b: c,d, __self: this, __source: {fileName: _jsxFileName, lineNumber: 1}}, e, f)
```

Babel output:
```js
"use strict";
var _jsxFileName = "/sample.tsx";
/*#__PURE__*/
React.createElement("a", {
  b: (c, d),
  __self: void 0,
  __source: {
    fileName: _jsxFileName,
    lineNumber: 1,
    columnNumber: 1
  }
}, (e, f));
```

Babel parenthesizes the comma operator expressions as needed for precedence, but Sucrase does not resulting in a wrong emit.

**Comment by alangpierce** [comment]
@nmain Thanks for the report! I agree that this is a bug.

Out of curiosity, did this come up in realistic code, or were you stress-testing Sucrase? I almost never see the comma operator in real-world code, though I imagine it may be more common for some coding styles.

I can think of two fixes here:
* Always surround all JSX values in parentheses, just in case there's a comma expression in the middle of them. This makes the JSX output a little uglier even when no comma operators are used.
* Add additional token/parser state so that the parser can detect when an expression has a comma operator, then surround the JSX value in parentheses in that case. This makes Sucrase a little slower and more complex even when no comma operators are used.

I'm a little hesitant with both of those, but would probably lean toward the first approach if I had to pick. But I'll think about it more; there may be another approach that doesn't impact the common case.

**Comment by nmain** [comment]
@alangpierce Thanks for the response!  This was found in real code, but the real code was most certainly written in error.  Since it wasn't my code but just code I had to support, my fix was to parenthesize the comma operator in the JSX.  If I was actually writing or improving the code, I would most certainly remove the comma operator usage entirely.

**Comment by alangpierce** [comment]
Interestingly, it looks like this case actually is actually disallowed by the JSX spec and accidentally allowed by Babel, but will be disallowed in Babel 8:
https://github.com/babel/babel/issues/8604
https://github.com/babel/babel/pull/8787

TypeScript flags the problem as an error here:
<img width="717" alt="Screen Shot 2021-07-03 at 11 16 00 PM" src="https://user-images.githubusercontent.com/211605/124375034-b2cbdb00-dc54-11eb-8f88-a890deac3b50.png">

That doesn't mean Sucrase can't/shouldn't implement support for this case, but it means that I'd be more hesitant about adding a lot of complexity or making the code output uglier to handle this case.

**Comment by nmain** [comment]
If the spec disallows it, that's good enough for me.
