### ISSUE TITLE
Failing transform of the d3 module

### ISSUE THREAD

**Issue by webschik** [alangpierce/sucrase#631]
Hello,

I found a bug in the transform of the next ES code https://sucrase.io/#compareWithTypeScript=true&compressedCode=H4sIAHD13mAAA2WNzQqDMBAG7z7FdzREiofSQyUtXvoewSQgaFLWbLDUvnvjz6k97S7DzNr5GSjCWKd5iHDsu9gHj47Hiccy6YHtVGGbwQm8C%2BSDkCEU6gq9N3Ze1yYTspHJ4zEEHS%2Fnlki%2FTo7CXwdKKXA2Xe%2BtySJwR4K6oVzDUkEmLAtqsbHrL9srZTreS3mUJ7Fboik%2BX9IsTqnaAAAA

The code is taken from `d3-array` module, https://github.com/d3/d3-array/blob/main/src/cumsum.js

**Comment by alangpierce** [comment]
Thanks for reporting! Looks like Babel also has trouble with that example on the Sucrase playground (which has an older version of Babel installed), but the most recent version of Babel seems to handle it fine. So it's possible that this could be fixed by porting Babel parser updates since the last port, or an approach could be to see how Babel ends up parsing it

**Comment by curran** [comment]
Related to https://github.com/alangpierce/sucrase/issues/666
