### ISSUE TITLE
TypeScript and ESM with @sucrase/jest-plugin

### ISSUE THREAD

**Issue by ide** [alangpierce/sucrase#664]
**Context:** TypeScript 4.5 (currently in beta) adds better support for ESM, namely [allowing .ts modules to import each other via .js import specifiers](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#ecmascript-module-support-in-nodejs):
```ts
// example.ts
import { something } from './dependency.js';
```
where `dependency.js` is actually `dependency.ts` on disk.

TypeScript needed to add this because Node's ESM implementation [requires file extensions](https://nodejs.org/api/esm.html#mandatory-file-extensions). `import './dependency'` is no longer valid and you must write `import './dependency.js'`.

This poses a problem for TypeScript, which historically has required people to write `import './dependency'` -- tsc would look for a file named `dependency.ts` and the compiled JavaScript with `require('./dependency')` would also work.

Mandatory file extensions with ESM in Node force relative imports to end in `.js` (or `.mjs` or `.cjs`), so TypeScript 4.5 now knows to look up `.ts` files (or `.mts` or `.cts`) files even when an import statement specifies a `.js` file.

**Sucrase:** I suspect Sucrase just works with this change since it doesn't resolve imports AFAICT. However, Sucrase's Jest plugin is affected and probably `sucrase-node`, too. Consider a test like this:

**index.ts**
```ts
export function demo(): void {}
```
**__tests__/index-test.ts**
```ts
import { demo } from '../index.js';  // note the .js extension

test(`runs`, () => { demo(); });
```

The Jest plugin compiles `index-test.ts` on the fly and runs it, and Node will look for `../index.js`, which doesn't exist since the file on disk has a `.ts` extension. (N.B. tests probably can use `.ts` extensions in their imports if they're always run with Sucrase, but if `index.ts` imported another module we'd have this same issue.)

**Solutions:**

1. Sucrase would rewrite import specifiers ending in`.js` to end in `.ts` instead and mimic tsc's resolution algorithm. Might require I/O depending on whether tsc allows `.js` imports to refer to `.mts` and `.cts` files.
2. Sucrase's Jest plugin would hook into [Node's ESM loaders](https://nodejs.org/api/esm.html#loaders) and simulate tsc's resolution algorithm there.

2 is probably better to keep Sucrase itself I/O-less but I'm not familiar enough with the ESM loader APIs to say if they'd even work here. That said, Sucrase is definitely not alone in this need -- every on-the-fly TypeScript runner needs this feature.

**Repro:** clone https://github.com/ide/sucrase-typescript-esm, install dependencies with Yarn, and run `yarn test`.

**Comment by alangpierce** [comment]
Hey @ide, thanks for surfacing and explaining the problem in such detail! You're right that Sucrase doesn't resolve imports and doesn't do any I/O, and it would be great if it could stay that way. The required file extension issue has been on my radar for a while, and it's definitely awkward to need to specify the file extension explicitly when really it depends on the build setup. It feels unfortunate to need `.js` extensions even for projects that never have intermediate `.js` files, but I can understand why the TS team did it that way.

I think your solution 1 (import rewriting) would definitely need I/O because we might be in a mixed TS/JS project. If we see `import { something } from './dependency.js';`, it might be referencing a `dependency.js` or `dependency.ts`, and Sucrase would need to figure out which of those two files actually exists.

I'm also not very familiar with ESM loaders, but I'm hoping they can provide a solution here.

Another thought: for Jest specifically, I'm not very familiar with the its internals, but I know it applies its own transforms and keeps a cache of transformed code, so I wonder if it has additional control over module resolution compared with the typical node algorithm. That might make it possible to have a Jest-specific solution for flexibly resolving imports.

(Another way this could work is for TS files to just use the .js extension, like Flow and JSX already do, but I guess that would be a pretty big shift and certainly have various downsides.)

**Comment by ide** [comment]
For Jest specifically, I found a simple solution for simple projects. Jest has a ["moduleNameMapper" option](https://jestjs.io/docs/configuration#modulenamemapper-objectstring-string--arraystring) that rewrites imports. It is constrained to use only regexes and capturing groups as opposed to functions, but is enough for this use case.

The approach is to look for all relative imports that end in ".js" and try looking them up as ".ts" files, falling back to the original filename if the rewritten ".ts" filename doesn't exist.

```json
"moduleNameMapper": {
  "^(\\.\\.?/.*)\\.js$": [
    "$1.ts",
    "$0"
  ]
}
```

This idea could be extended to support .jsx, .mjs, and .cjs files as well as module aliases (e.g. "~/x.js").

More generally, `sucrase-node`/`-r sucrase/register` may need some kind of mapper and having `@sucrase/jest-plugin` share the same mapper would create parity between the different ways of using Sucrase. E.g. `sucrase.config.js` could export an async function that rewrites import specifiers.

If this worked with pure Sucrase, too, I would actually find this quite useful since `tsc` uses the "paths" option in tsconfig.json to resolve modules but [doesn't rewrite imports in emitted JS](https://github.com/microsoft/TypeScript/issues/26722). This means projects that use path aliases need to rewrite imports with Babel/jscodeshift/etc. after `tsc`.

That said, Jest's moduleNameMapper addresses this well enough for the Jest use case. Will close this out.
