### ISSUE TITLE
Sucrase can't transpile d3-array

### ISSUE THREAD

**Issue by ninofiliu** [alangpierce/sucrase#666]
Over here at @toucantoco we're using Sucrase and we're quite happy with it, thanks for maintaining it! However after a deps update we can't run the tests anymore because it looks like Sucrase can't properly transpile [this file](https://github.com/d3/d3-array/blob/416f657e932690f5e023f9ced6f7cadf118b00ac/src/cumsum.js)

As you can see in [this Sucrase playground](https://sucrase.io/#selectedTransforms=typescript&compressedCode=H4sIAHoYlWEAA2WNzQqDMBAG7z7FdzREiofSQyUtXvoewSQgaFLWbLDUvnvjz6k97S7DzNr5GSjCWKd5iHDsu9gHj47Hiccy6YHtVGGbwQm8C%2BSDkCEU6gq9N3Ze1yYTspHJ4zEEHS%2Fnlki%2FTo7CXwdKKXA2Xe%2BtySJwR4K6oVzDUkEmLAtqsbHrL9srZTreS3mUJ7Fboik%2BX9IsTqnaAAAA) by checking and unchecking this `typescript` option, Sucrase fails when TS is on

However this is valid TS, and as you can see in [this TS playground](https://www.typescriptlang.org/play?ssl=6&ssc=1&pln=6&pc=2#code/KYDwDg9gTgLgBAE2AMwIYFcA29noHYDGMAlhHnAegLYDO1AFAG6qbrA0A0czrwEyASjgBvAFBxuqKHDpU4AXjgAGLsTxIQC5QG5xcKMBjoo5AGKYIqGADYALAEEoUVAE8AdMigQqTFm06SvPwK8or4SMhqwAh6EgD83AoAfHD0snAA1IoZjHAAPnnKArFwAFyJ8ilp1JnZPGz8TKrqoBkZXPXsQgVFAroAvkA), this properly transpiles to JS, and if `noImplicitAny` is set to `false` there is no error

I don't know why this happens when running our tests since [@sucrase/jest-plugin precises](https://github.com/alangpierce/sucrase/tree/main/integrations/jest-plugin) that a `.js` will not be transpiles with the typescript option

Anyway just wanted to give you a heads up on this, I have no idea how to fix it yet but I can try if you guys are too busy

**Comment by ninofiliu** [comment]
Nevermind what I said about typescript - as @prettywood noticed, the flow transform has the same effect of making the transpilation crash, which explains why the sucrase plugin can't transpile

**Comment by ninofiliu** [comment]
This is [the shortest code](https://sucrase.io/#selectedTransforms=flow&code=0%20%3F%20a%20%3D%3E%20(a%20%2B%3D%200)%20%3A%20a%20%3D%3E%200) I came up with that triggers the same error

```js
0 ? a => (a += 0) : a => 0
```

**Comment by curran** [comment]
Interestingly, if you put parens around `a => 0`, it [works fine](https://sucrase.io/#selectedTransforms=flow&code=0%20%3F%20a%20%3D%3E%20(a%20%3D%205)%20%3A%205).

```
0 ? a => (a += 0) : (a => 0)
```

I wonder where the problem could lie...

**Comment by alangpierce** [comment]
Thanks for reporting, I'm getting back to Sucrase maintenance now and this is definitely a tricky one! Working on it now and I'm not totally sure how to fix, but I figure writing down some thoughts may help.

Babel ran into the same bug and fixed it here: https://github.com/babel/babel/pull/13581/files . Unfortunately, that fix is a rare situation where the Babel parser inspects its partially-created AST and uses it to make parsing decisions. Sucrase intentionally avoids creating an AST, so there isn't an obvious equivalent of the fix for Sucrase.

In general, arrow functions are among the hardest things to parse in JS, and TS makes them even more complicated. If you're reading the code token-by-token and see `(a = 1, b = 2)`, there's no way to know if you're dealing with two variable assignments separated by the comma operator, or if this is the start of an arrow function with two parameters with default values. It's only when seeing the next token after the `)` that you can distinguish those two situations; for example, if you see a `=>` token, then this must actually be an arrow function. Babel's strategy is take the incorrectly-parsed comma operator AST and rewrite it so that it instead represents arrow parameters. Sucrase doesn't have an AST but still needs to correctly indicate `IdentifierRole` for the params, so it does a restore-from-snapshot to before the `(` and re-parses the expression as an arrow function. In both cases, the relevant function is `parseParenAndDistinguishExpression`. TypeScript syntax needs extra care because `:` after a parenthesized list might indicate the return type of the arrow function.

In the example failing code, Sucrase (and Babel before the bug fix) is seeing `(PARAMETERS) : a => 0`, which is a valid arrow expression where `a` is the return type. Babel's fix is to inspect the AST for `PARAMETERS`, see that `a += 0` isn't actually a valid parameter declaration, and bail out of the arrow parsing case. Sucrase might need to detect that distinction up-front or have a fallback when the arrow case later doesn't parse correctly. I'll also take a look at how the TypeScript parser handles it; it might take an approach that's easier to incorporate into Sucrase.

**Comment by ninofiliu** [comment]
Update: the d3-array maintainer refuses to add two parenthesis which would fix Sucrase not transpiling d3-array (for good reasons I think) https://github.com/d3/d3-array/pull/242#issuecomment-1005973529

**Comment by ninofiliu** [comment]
Allowing the Sucrase Jest plugin not to use the Flow transform on .js files would allow Sucrase Jest plugin users to bypass the issue

I have the bandwith to suggest a PR allowing Sucrase Jest plugin users to configure it as such

```jsonc
{
  "transform": {
    // uses default transforms
    "\\.js$": ["@sucrase/jest-plugin"],
    // uses custom transforms
    "\\.jsx$": ["@sucrase/jest-plugin", { "transforms": ["jsx", "imports", "jest"] }]
  }
}
```
