### ISSUE TITLE
Hello, how use sucrase-node

### ISSUE THREAD

**Issue by DhanielB** [alangpierce/sucrase#718]
How i use sucrase-node calling in internally js like README.md of this project speaks

Example : 

This is just an example (since it doesn't exist in sucrase declarations)

```js
import { sucrase_node } from "sucrase"

async function main() {
  const response = await sucrase_node.run("file.js")

  console.log(response)
}
```

Is there any way to run sucrase-node like this?

**Comment by alangpierce** [comment]
Hi @DhanielB , sucrase-node is intended as a standalone executable, so it doesn't have a direct JS API like that. `sucrase-node` is really just a simple wrapper script that uses `sucrase/register` and then runs node. You can see the code here: https://github.com/alangpierce/sucrase/blob/main/bin/sucrase-node

A few options come to mind, depending on what you're trying to do:

If you're just trying to run another file in node with Sucrase enabled, the easiest way is something like this:
```js
require("sucrase/register");
require("./file.js");
```
The register line sets up the require hook so that all `require` calls from now on will transform the code to remove type annotations, transform JSX, and convert `import` to `require`.

If you're trying to create a *new process* without registering any hooks in the current node process, you can use Node's `child_process` module, which has a few ways of creating child processes and getting their result (stdout, stderr, exit code). Here's an example that works in node 18 if this runner file ends in `.mjs`:
```js
import {promisify} from "node:util";
import {exec} from "node:child_process";

const execPromise = promisify(exec);

async function main() {
  const result = await execPromise("./node_modules/.bin/sucrase-node ./file.js");
  console.log(result.stdout);
}

main();
```
Or if you don't want to deal with the ESM (`.mjs`/`import`) details, you can use plain `require` (e.g. `require("node:util")`) for the outer script that's invoking sucrase-node. Another option is to invoke `"node -r sucrase/register ./file.js"` rather than `sucrase-node`.

Hope that helps point you in the right direction! Closing this issue since I've answered the question, but feel free to comment more if you want.
