### ISSUE TITLE
Add ts-node transpiler plugin

### ISSUE THREAD

**Issue by alangpierce** [alangpierce/sucrase#726]
ts-node now allows a configurable transpiler and already has built-in support for swc. It would be great for Sucrase to provide plugin as well. I'm hoping to work on this soon, just filing for tracking purposes.

Docs are here: https://typestrong.org/ts-node/docs/transpilers/

For ts-node users, this would be a nice drop-in replacement to speed up the transpile step. I already prototyped a quick plugin and ran it through a stress test of a 1 million line codebase and confirmed that ts-node with Sucrase is almost 2x faster than ts-node with swc for handling the initial transpile/import. I'll make sure to include a reproducible benchmark as part of this work, similar to the benchmark already on the README.

For Sucrase users, this would be a more polished and feature-complete alternative to `sucrase/register` and `sucrase-node`, which are both fairly simple integrations using the `pirates` library. Most significantly, this would make it easy to use Sucrase for ESM in node via ts-node's loader hook. I've been investigating adding an ESM loader hook for Sucrase, but there are certainly some details to work through, and it would be nice to just integrate with a library that already handles it all. In addition to ESM support, ts-node also has a REPL and would allow configuration (e.g. JSX config) via tsconfig.json.

In terms of implementation, it looks like there are some compile modes that would need to be supported, e.g. targeting commonjs but preserving dynamic `import()`, so those are also options that should be added to Sucrase as part of this work.

Some open questions:
* Should the integration be a separate package (living in the `integrations` directory) or part of the core `sucrase` package? It looks like it should be possible to write without taking on any additional dependencies. Making it part of `sucrase` seems ideal as a way to quickly get started.
* Should this ts-node integration *replace* `sucrase/register` and `sucrase-node` (as a future breaking change)? My leaning is to keep Sucrase's integrations as a lighter-weight way of supporting the common case, but it may make sense to down-scope Sucrase to purely a transpile function, since that's where I've mostly focused anyway. There are also plenty of non-TypeScript cases (e.g. Flow or a Babel-like JSX/imports setup without tsconfig) that Sucrase supports.
* Similarly, is it worth adding a built-in Sucrase loader hook when there's already a ts-node integration? My leaning is yes for similar reasons as above. But this may depend on the details of how complex a loader hook turns out to be.

**Comment by cspotcode** [comment]
Follow-up from my comment https://github.com/nodejs/node/issues/43818#issuecomment-1196849289

Are you interested in getting sucrase support added as a dedicated `"sucrase": true` flag in ts-node?  It can still live as a separate package, so you'll still have ownership of it.  But is the dedicated flag a good thing for user experience, or no?

Right now, the swc transpiler integration lives with ts-node, so when someone sets `"swc": true` that's equivalent to `"transpiler": "ts-node/transpilers/swc"`  Then that integration tries to `require("@swc/core")`  The integration is bundled, but the swc compiler is a peer dependency.

For sucrase, could be a bit different: the integration can be part of the peer dependency, not bundled.  But otherwise similar:
`"sucrase": true` is equivalent to `"transpiler": "sucrase/ts-node"` or wherever you decide it should live.

The next release of ts-node is going to be a major, so I can make breaking changes to the transpiler plugin API if we want.  I've had to tweak the API over time, to support unanticipated issues with the swc integration.  But till now, I've been the sole consumer of the API, at least as far as I'm aware.  Any feedback you have is appreciated.

**Comment by alangpierce** [comment]
Hi @cspotcode, thanks for reaching out, and thanks for all the great work you've done on ts-node!

Yes, `"sucrase": true` or `--sucrase` would be wonderful, I was planning to ask about that. I like the general strategy of having easy-to-use recommended transpilers while also leaving it open for anyone else who wants to add their own.

Good question about where the integration should live and how to handle possible breaking changes both on the ts-node side and the Sucrase side. I'm planning on some upcoming breaking changes in Sucrase, so it seemed useful to have the integration live there, though if the plugin interface is going through a lot of breaking changes, it might be smoother for it to live on the ts-node side. Let's plan on it living in Sucrase for now, but can coordinate.

Overall the plugin interface has been pretty smooth. The fact that `create` is called 5 times was surprising at first, but also was helpful in understanding the nuances around how TS deals with `.cts` and `.mts` files. I have a few minor thoughts/questions on the plugin interface, and would be great to get your eyes on the details. I'll put up a draft PR of what I have so far and can tag you in some specifics.
