### ISSUE TITLE
Support for transpiling imports with `assert {type: "json"}` to use the old native way of node:fs ?

### ISSUE THREAD

**Issue by renhiyama** [alangpierce/sucrase#744]
Consider looking at this code: https://deno.land/x/emoji@0.2.1/emoji.ts?source
It has `assert`, which crashes sucrase:
![image](https://user-images.githubusercontent.com/92968534/189516084-ce28a5a3-5fea-491b-a5ef-fc53f593b602.png)

The 4th line has `assert`.

**Comment by alangpierce** [comment]
@renhiyama thanks for the report! I filed a tracking issue a while back as https://github.com/alangpierce/sucrase/issues/566 , but I know this syntax is becoming more common, so definitely seems time to add better support. Could you clarify more specifically what you mean by "the old native way of node:fs"? Is there another transpiler that has the behavior you want that I could model the implementation off of?

I think the behavior I'd be most comfortable with is this:
* When targeting CJS (when `imports` is specified as a transform), the `import` becomes a `require` as usual and the `assert {type: "json"}` is ignored/removed. This should work with node because `require` handles JSON files automatically.
* When targeting ESM (when `imports` is not specified as a transform), the import assertion is passed through as-is, so the output code has the `assert { type: "json" };`. I just confirmed that this works on node 16+ when using node's native ESM support.

Would that work for your use case?

**Comment by renhiyama** [comment]
Oh i didn't knew it was supported in nodejs v16! Yea then we can continue with what you said above! (I didn't test a json import but I remember doing it last year) looking forward for the fix since a lot of deno modules use that and I need a way to get them too!

**Comment by renhiyama** [comment]
hey @alangpierce , when are you publishing a new version of sucrase so I can start using it in my projects?

**Comment by alangpierce** [comment]
Just released as 3.27.0, let me know if you see issues!

**Comment by renhiyama** [comment]
Worked!
![image](https://user-images.githubusercontent.com/92968534/190693478-72b8e4b8-b263-4bcd-b74e-b900a1fe2a25.png)
Cheers 🎉
