### ISSUE TITLE
Failure to parse some usages of Flow $Call (Unexpected token, expected ",")

### ISSUE THREAD

**Issue by zipang** [alangpierce/sucrase#758]
Sucrase fails to parse some usages of the type helper `$Call` inside Flow code :

Example of code failing : 

```js
// @flow

type Account = $PropertyType<
  $Call<<T>($ReadOnlyArray<T>) => T>,
  'account'
>
```

Demo :
* [Sucrase (failing)](https://sucrase.io/#transforms=flow&code=%2F%2F%20%40flow%0A%0Atype%20Account%20%3D%20%24PropertyType%3C%0A%20%20%24Call%3C%3CT%3E(%24ReadOnlyArray%3CT%3E)%20%3D%3E%20T%3E%2C%0A%20%20'account'%0A%3E)
* [Flow compiler (accepted)](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCAxsXAK4B2GYAvGACQAKATnPi9gCq54A8qMIwDCAQxgw+fLgD4AFAwBKeUQBMA8pRhZCLFqKzSZASjoywsgDSCwAclGkK1W6hmogA)

**Comment by alangpierce** [comment]
Thanks for reporting! I think the bug here is that `<<` being mis-tokenized as a left-shift operator. There are already some special cases to get `>>` working (based off of similar special cases in Babel), and at least one `<<` case was handled recently in https://github.com/alangpierce/sucrase/pull/716/files#diff-0221cac4ed46c5209e9fe0f67d5f903e3f2069287eedc8a8502f3906f504ac2c , but looks like this is a case that was missed.

**Comment by zipang** [comment]
Thxx a lot ! :)
