### ISSUE TITLE
(plugin commonjs--resolver) Syntax Error when importing file with json import

### ISSUE THREAD

**Issue by felixhaeberle** [alangpierce/sucrase#796]
### Description

I have the following problem with Sucrase:

```sh
inlang-vs-code-extension:dev: [!] (plugin commonjs--resolver) SyntaxError: Error transforming /Users/felixhaberle/Desktop/git/inlang/node_modules/dotenv/package.json: Unexpected token, expected ";" (2:9)
inlang-vs-code-extension:dev: ../../node_modules/dotenv/lib/main.js (2:9)
inlang-vs-code-extension:dev: at unexpected (/Users/felixhaberle/Desktop/git/inlang/node_modules/sucrase/dist/parser/traverser/util.js:99:15)
inlang-vs-code-extension:dev: at semicolon (/Users/felixhaberle/Desktop/git/inlang/node_modules/sucrase/dist/parser/traverser/util.js:77:5)
```

It seems that Sucrase cannot parse the imported package.json from the dotenv package.

Is it possible to set it up in a way that the parser can actually parse that file?

Thank you in advance!! ✨

**Comment by alangpierce** [comment]
Hi @felixhaeberle , sorry for the delay, and thanks for reporting. I think this is an issue in your configuration rather than a problem that can be reasonably fixed on the Sucrase side. I see `commonjs--resolver` in your error message, so my guess is you're using rollup, and from a little testing on my end, it looks like you may need to add `@rollup/plugin-json` so that it will detect `.json` files and handle them separately rather than trying to transpile them. I wasn't seeing those exact messages, so you may be using a different tool or variation, but in any case, I'd see if there's some similar solution of skipping Sucrase entirely for JSON files.

In general, all JS parsers will fail for typical JSON files, not just Sucrase. You might think that JSON is always valid JS, but `{` at the start of a line is interpreted as the start of a block, not the start of an object, so `{"foo": "bar"}` is a syntax error.
