### ISSUE TITLE
Dont remove `export interface` , instead rename it to something else.

### ISSUE THREAD

**Issue by renhiyama** [alangpierce/sucrase#830]
Due to how Sucrase can't read other related files, it cant remove import statements that imports the interfaces.
So sucrase seems to only remove the exported variable completely, while not removing the imports, hence breaking the code.
The simplest and easiest suggestion I can give is to rename the `export interface <var> {...}` to something like to `export const <var> = 0;` So it doesn't break anything while removing typescript code as expected.
![Screenshot_20240223_211239_Termux](https://github.com/alangpierce/sucrase/assets/92968534/9c7c4f5f-8d66-4de7-9b78-2ef886b41e9e)

**Comment by easrng** [comment]
Can't you just import types explicitly as types `import { type GlobOptions } from "..."`?

**Comment by renhiyama** [comment]
> Can't you just import types explicitly as types `import { type GlobOptions } from "..."`?

that's not what this issue is about. Sucrase seems to break any code that exports interfaces when converting any typescript code to javascript. In order to not break any compability issues, my suggestion posted above is the only solution.

Your suggestion doesn't make sense because sucrase's point is to make stuff work, without needing much changes, nor break anything up.

**Comment by renhiyama** [comment]
@alangpierce could you please look at this issue asap?

**Comment by alangpierce** [comment]
Hi @renhiyama, unfortunately your suggestion of `export const <var> = 0;` is out of scope for Sucrase. Sucrase tries to match the behavior of TypeScript `transpileModule` as closely as possible (with minor exceptions), since it's meant to be a faster drop-in replacement. Babel, swc, and esbuild take the same approach, so this issue you're raising is a general issue (which already has some solutions, see below), not specific to Sucrase. See this [playground link](https://sucrase.io/#transforms=typescript&compareWithTypeScript=true&code=%0Aexport%20interface%20Foo%20%7B%7D) for how the output compares. If Sucrase did produce a runtime-visible export, it cause bugs for code iterating through a `*` import, or might conflict with an explicit value export.

The typical way to avoid the error you're seeing is to ensure that the code is removed on the `import` side. There are two historical ways this has been done:
* Automatic import elision. The default behavior for both TypeScript and Sucrase is to detect that `GlobOptions` is only used as a type, and to remove that import line (or just the one named import) in the resulting JS. The `isolatedModules` TypeScript option can help flag some issues like re-exports that can cause issues here.
* Explicit `type` syntax in the import. With Sucrase `keepUnusedImports` and TypeScript `verbatimModuleSyntax` (and its deprecated alternatives), the way to remove type imports is to explicitly write `type GlobOptions`.

Happy to reconsider if I'm overlooking a case where TypeScript (or another tool) emits a `const` declaration like you're talking about, but generally Sucrase follows TypeScript's lead on how file-by-file transpilation should work.
